{% set name = "metagraph-cuda" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
#  url: https://github.com/ContinuumIO/{{ name }}/archive/v{{ version }}.tar.gz
#  sha256: --- FILL THIS IN ---
  path: ../

build:
  number: 0

requirements:
  build:
    - python >=3

  host:
    - python >=3

  run:
    - python >=3

about:
  home: https://github.com/ContinuumIO/metagraph-cuda
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A collection of metagraph plugins for NVIDIA GPUs'
  dev_url: https://github.com/ContinuumIO/metagraph-cuda
