name: mgc

channels:
- rapidsai
- nvidia
- conda-forge

dependencies:
# dev environment
  - python=3.7
  - coverage
  - pytest
  - pytest-cov
  - black
  - conda-forge::pre-commit
  - setuptools

# metagraph dependencies
  - importlib_metadata
  - numpy
  - networkx
  - pandas
  - conda-forge::python-louvain
  - scipy
  - conda-forge::donfig
  - conda-forge::grblas

# metagraph-cuda dependencies
  - numba
  - cupy
  - cudf
  - cugraph=0.15.*
  - cudatoolkit=10.1
  - dask-cudf
  - dask-cuda

