name: mg
dependencies:
# dev environment
  - python=3.7
  - coverage
  - pytest
  - pytest-cov
  - black

# metagraph dependencies (so setup.py develop doesn't pip install them)
  - metagraph::metagraph
