name: Build

on:
  # Run this workflow every time a PR is opened or a new commit is pushed to the PR
  pull_request:
  # Run this workflow every time a PR is merged to main
  push:
    branches:
      - main

env:
  MAIN_PYVER: 3.8

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: mg
          environment-file: continuous_integration/environment.yml
      - name: Lint with Black
        run: |
          black --version
          black metagraph_cuda *.py --check --diff
      - name: Conda Build
        run: |
          conda install -q conda-build
          conda build --no-test -c defaults -c metagraph/label/dev -c rapidsai -c conda-forge --python ${{ env.MAIN_PYVER }} continuous_integration/conda
          # This doesn't rebuild, but simply computes the name of the file that was previously built
          OUTPUT=$(conda build --output -c defaults -c metagraph/label/dev -c rapidsai -c conda-forge --python ${{ env.MAIN_PYVER }} continuous_integration/conda)
          echo "Path to built package:"
          echo $OUTPUT
          echo "CONDA_BUILD_OUTPUT=$OUTPUT" >> $GITHUB_ENV
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: built_package
          path: ${{ env.CONDA_BUILD_OUTPUT }}
          retention-days: 7

  dev_deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: built_package
          path: ./artifact_storage
      - name: Deploy with dev label
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda config --set always_yes yes --set changeps1 no
          conda install -q anaconda-client
          ls -la ./artifact_storage
          UPLOAD=`ls ./artifact_storage | head -1`
          echo "Uploading $UPLOAD with label=dev"
          $CONDA/bin/anaconda -t ${{ secrets.ANACONDA_ORG_TOKEN }} upload -u metagraph -l dev --no-progress --force --no-register ./artifact_storage/$UPLOAD

