package:
  name: metagraph-cuda
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}
  string: {{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - metagraph

  run:
    - python
    - setuptools
    - metagraph
    - cudf
    - cupy
    - cugraph

test:
  requires:
    - pytest
    - cudf
    - cugraph
    - pandas
    - networkx
#    - pytest-cov
#    - coverage
#    - black

  commands:
    - pytest --pyargs metagraph_cuda.tests

about:
  home: https://github.com/metagraph-dev/metagraph-cuda
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Metagraph plugins for NVIDIA GPUs'
  description: |
      Plugins for running graph algorithms on NVIDIA GPUs.
  dev_url: https://github.com/metagraph-dev/metagraph-cuda
